version: "2.2"
services:
  iris:
    init: true
    image: intersystemscommunity/pexdemo:latest
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - 'jgw'
#      - 'netgw'
    ports:
      - 9980:9980
      - 52773:52773
      - 51773:51773
      - 55555:55555

